### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by bergel** [aserg-ufmg/RefDiff#1]
It would be fantastic if a kind of tutorial could be provided in the README file. Currently, it is hard to grasp the expressiveness of RefDiff just by reading the README file

**Comment by danilofes** [comment]
Dear Bergel,

I have added more info in the README, along with a first version of a tutorial:
https://github.com/aserg-ufmg/RefDiff/blob/master/doc/Tutorial1.md

We intend to keep improving the docs. Let me know if you have other suggestions.

Thanks
