### ISSUE TITLE
Would it be possible to publish a recent release of RefDiff?

### ISSUE THREAD

**Issue by vanilson** [aserg-ufmg/RefDiff#7]
It would be great if a new release of RefDiff could be used as a gradle or maven dependency.

**Comment by Jirigesi** [comment]
Is there any similar tool for python? or how can I use this for python code?

**Comment by danilofes** [comment]
Hi @vanilson, RefDiff 2.0.0 is finally published at Maven central:

https://search.maven.org/search?q=refdiff

Sorry for the long delay.
