### ISSUE TITLE
Is it possible to use this tool for python code?

### ISSUE THREAD

**Issue by Jirigesi** [aserg-ufmg/RefDiff#8]
Hi, 

Thanks for this excellent tool! Can I use this for python? or is there a similar tool for python code? 

Thanks

**Comment by danilofes** [comment]
Hi @Jirigesi. Thanks for your interest! In theory, it would be possible to extend RefDiff to support other languages. It would be really nice to have Python support but, unfortunately, this is not in our plans for the near future. I also don't know of any other tool that offers such support. I will close this issue for now.
